version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.27
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      retries: 5
    networks:
      - local-01

  api:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks: 
     - local-01

networks:
  local-01:
    driver: bridge